CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar,
  "password_hash" varchar,
  "is_admin" bool
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "created_at" datetime
);

CREATE TABLE "product_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku" varchar UNIQUE,
  "name" varchar,
  "product_type" varchar,
  "price" decimal(12,2),
  "availability_status" varchar,
  "category_id" int
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL,
  "price" decimal(12,2)
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city" varchar,
  "street" varchar,
  "house" varchar,
  "apartment" varchar,
  "comment" text
);

CREATE TABLE "service_objects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "object_type" varchar,
  "area" decimal(12,2),
  "address_id" int UNIQUE
);

CREATE TABLE "service_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" varchar UNIQUE,
  "type" varchar,
  "status" varchar,
  "description" text,
  "service_object_id" int
);

CREATE TABLE "install_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_request_id" int UNIQUE NOT NULL,
  "date" date
);

CREATE TABLE "repair_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_request_id" int UNIQUE NOT NULL,
  "date" date
);

CREATE TABLE "estimates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_request_id" int UNIQUE NOT NULL,
  "labor_cost" decimal(12,2),
  "material_cost" decimal(12,2),
  "status" varchar
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_request_id" int NOT NULL,
  "text" text,
  "sent_at" datetime
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" varchar UNIQUE,
  "created_at" datetime,
  "status" varchar,
  "total_amount" decimal(12,2),
  "service_request_id" int UNIQUE,
  "address_id" int
);

CREATE TABLE "deliveries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int UNIQUE NOT NULL,
  "address_id" int,
  "type" varchar,
  "cost" decimal(12,2),
  "eta" datetime
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "method" varchar,
  "amount" decimal(12,2),
  "status" varchar,
  "paid_at" datetime
);

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "service_objects" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "service_requests" ADD FOREIGN KEY ("service_object_id") REFERENCES "service_objects" ("id");

ALTER TABLE "install_requests" ADD FOREIGN KEY ("service_request_id") REFERENCES "service_requests" ("id");

ALTER TABLE "repair_requests" ADD FOREIGN KEY ("service_request_id") REFERENCES "service_requests" ("id");

ALTER TABLE "estimates" ADD FOREIGN KEY ("service_request_id") REFERENCES "service_requests" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("service_request_id") REFERENCES "service_requests" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("service_request_id") REFERENCES "service_requests" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "deliveries" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "deliveries" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
