@startuml
title Сценарий использования игроком

start

:Авторизация пользователя;
if (Авторизация успешна?) then (да)
  :Отображение вкладки Explore;
  :Загрузка рекомендаций;
else (нет)
  stop
endif

:Игрок выбирает игру из рекомендаций;
:Открытие страницы игры в новом окне;
:Показ информации об игре (описание, обложка, отзывы);

:Игрок выставляет оценку (1-5);
:Сохранение оценки в системе;

if (Пользователь хочет написать ревью?) then (да)
  :Ввод комментария;
  :Сохранение ревью в системе;
else (нет)
endif

:Обновление рекомендаций при изменении предпочтений или при скролле;

stop
@enduml
